export const AUTH = {
  LOGIN: 'AUTH/LOGIN',
  LOGOUT: 'AUTH/LOGOUT'
};

export const TOKEN = {
  LOGIN: 'TOKEN/SET',
  LOGOUT: 'TOKEN/GET'
};

export const SYSTEM = {
  FETCH_SYSTEM: 'SYSTEM/FETCH_SYSTEM',
  FETCH_SYSTEM_SUCCESS: 'SYSTEM/FETCH_SYSTEM_SUCCESS'
};

export const CUSTOMER = {
  FETCH_CUSTOMER: 'CUSTOMER/FETCH_CUSTOMER',
  FETCH_CUSTOMER_SUCCESS: 'CUSTOMER/FETCH_CUSTOMER_SUCCESS'
};

export const NERD = {
  QUERY_NERD: 'NERD/QUERY_NERD',
  QUERY_NERD_SUCCESS: 'NERD/QUERY_NERD_SUCCESS'
};
