export const AUTH = {
  LOGIN: 'AUTH/LOGIN',
  LOGOUT: 'AUTH/LOGOUT',
};

export const TOKEN = {
  LOGIN: 'TOKEN/SET',
  LOGOUT: 'TOKEN/GET',
};

export const SYSTEM = {
  FETCH_SYSTEM: 'SYSTEM/FETCH_SYSTEM',
};

export const CUSTOMER = {
  FETCH_CUSTOMER: 'CUSTOMER/FETCH_CUSTOMER'
};

export const NOTIFICATION = {
  ADD_NOTIFICATION: 'NOTIFICATION/ADD_NOTIFICATION'
};
